require('./setting/airport_code_app');
require('./setting/bank_app');
require('./setting/brand_app');
require('./setting/country_app');
require('./setting/currency_app');
require('./setting/currency_conversion_app');
require('./setting/harbour_app');
require('./setting/holiday_type_app');
require('./setting/hotel_app');